[build]
  command = "npm run build"
  publish = "dist/public"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "20"
  CI = "false"
  NODE_OPTIONS = "--max_old_space_size=4096"
  
[dev]
  command = "npm run dev"
  port = 5000
  publish = "dist/public"
